# Prometheus Configuration for Dorfkiste
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'dorfkiste-monitor'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093
      timeout: 10s
      api_version: v2

# Load rules once and periodically evaluate them
rule_files:
  - "alerts/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # Dorfkiste Application
  - job_name: 'dorfkiste-app'
    static_configs:
      - targets: ['app:3000']
    metrics_path: '/api/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s
    params:
      format: ['prometheus']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: app:3000

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # PostgreSQL Database
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 15s

  # Redis Cache
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 15s

  # Nginx Reverse Proxy
  - job_name: 'nginx-exporter'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 15s

  # Blackbox Exporter for external monitoring
  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://yourdomain.com
        - https://yourdomain.com/api/health
        - https://yourdomain.com/api/items
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # SSL Certificate Monitoring
  - job_name: 'blackbox-ssl'
    metrics_path: /probe
    params:
      module: [tcp_connect]
    static_configs:
      - targets:
        - yourdomain.com:443
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # Docker Container Metrics (if using Docker)
  - job_name: 'docker'
    static_configs:
      - targets: ['docker-exporter:9323']
    scrape_interval: 15s

  # Custom Application Metrics
  - job_name: 'dorfkiste-business-metrics'
    static_configs:
      - targets: ['app:3000']
    metrics_path: '/api/metrics/business'
    scrape_interval: 60s
    params:
      format: ['prometheus']

# Recording rules for pre-computed queries
recording_rules:
  - name: dorfkiste.rules
    rules:
      # HTTP Request Rate
      - record: dorfkiste:http_requests:rate5m
        expr: rate(http_requests_total[5m])
      
      # HTTP Error Rate
      - record: dorfkiste:http_errors:rate5m
        expr: rate(http_requests_total{status=~"5.."}[5m])
      
      # Response Time Percentiles
      - record: dorfkiste:http_request_duration:p95
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m]))
      
      - record: dorfkiste:http_request_duration:p99
        expr: histogram_quantile(0.99, rate(http_request_duration_seconds_bucket[5m]))
      
      # Database Query Performance
      - record: dorfkiste:db_query_duration:p95
        expr: histogram_quantile(0.95, rate(db_query_duration_seconds_bucket[5m]))
      
      # Active Users (business metric)
      - record: dorfkiste:active_users:1h
        expr: increase(user_login_total[1h])
      
      # Revenue Metrics
      - record: dorfkiste:revenue:daily
        expr: increase(payment_completed_total[1d])

# Alert rules
alert_rules:
  - name: dorfkiste.alerts
    rules:
      # High Error Rate
      - alert: HighErrorRate
        expr: dorfkiste:http_errors:rate5m > 0.1
        for: 5m
        labels:
          severity: critical
          service: dorfkiste
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value }} errors per second"
      
      # High Response Time
      - alert: HighResponseTime
        expr: dorfkiste:http_request_duration:p95 > 2
        for: 5m
        labels:
          severity: warning
          service: dorfkiste
        annotations:
          summary: "High response time detected"
          description: "95th percentile response time is {{ $value }}s"
      
      # Database Connection Issues
      - alert: DatabaseConnectionIssues
        expr: up{job="postgres-exporter"} == 0
        for: 2m
        labels:
          severity: critical
          service: database
        annotations:
          summary: "Database connection lost"
          description: "PostgreSQL database is not responding"
      
      # Redis Connection Issues
      - alert: RedisConnectionIssues
        expr: up{job="redis-exporter"} == 0
        for: 2m
        labels:
          severity: warning
          service: redis
        annotations:
          summary: "Redis connection lost"
          description: "Redis cache is not responding"
      
      # Application Down
      - alert: ApplicationDown
        expr: up{job="dorfkiste-app"} == 0
        for: 1m
        labels:
          severity: critical
          service: dorfkiste
        annotations:
          summary: "Dorfkiste application is down"
          description: "The main application is not responding"
      
      # SSL Certificate Expiring
      - alert: SSLCertificateExpiring
        expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 30
        for: 1h
        labels:
          severity: warning
          service: ssl
        annotations:
          summary: "SSL certificate expiring soon"
          description: "SSL certificate expires in {{ $value | humanizeDuration }}"
      
      # High Memory Usage
      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes > 0.9
        for: 5m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "High memory usage"
          description: "Memory usage is {{ $value | humanizePercentage }}"
      
      # High CPU Usage
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "High CPU usage"
          description: "CPU usage is {{ $value }}%"
      
      # Disk Space Low
      - alert: DiskSpaceLow
        expr: (node_filesystem_avail_bytes / node_filesystem_size_bytes) < 0.1
        for: 5m
        labels:
          severity: critical
          service: system
        annotations:
          summary: "Disk space low"
          description: "Disk space is {{ $value | humanizePercentage }} full"
      
      # Payment Processing Issues
      - alert: PaymentProcessingIssues
        expr: rate(payment_failed_total[5m]) > 0.05
        for: 5m
        labels:
          severity: critical
          service: payments
        annotations:
          summary: "High payment failure rate"
          description: "Payment failure rate is {{ $value }} failures per second"

# Storage configuration
storage:
  tsdb:
    retention.time: 30d
    retention.size: 10GB
    path: /prometheus/data
    wal-compression: true